# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('document_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('module', models.CharField(max_length=64)),
                ('skill', models.CharField(blank=True, default='', max_length=128)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('file_url', models.TextField(blank=True, default='')),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=36)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('retrievable', '可检索'), ('failed', '失败')], default='uploaded', max_length=16)),
            ],
            options={
                'db_table': 'knowledge_documents',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('chunk_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('embedding_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('retrieval_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('use_case', models.CharField(choices=[('teaching', '教学'), ('test_generation', '测试生成'), ('explanation', '解析'), ('retest', '重测'), ('risk', '风险')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='teaching.teachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retrieval_logs',
            },
        ),
    ]
