# Generated by Django 6.0.5 on 2026-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_beginner_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='risk_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='scenario_tags',
            field=models.JSONField(default=list),
        ),
    ]
