# Generated by Django 6.0.5 on 2026-05-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_add_metadata_fields'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievallog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='teaching.teachingsession'),
        ),
    ]
