# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperationLog',
            fields=[
                ('log_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=36)),
                ('export_format', models.CharField(blank=True, default='', max_length=10)),
                ('export_scope', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_operation_logs',
            },
        ),
    ]
