# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('prefer_not_to_say', '不愿透露')], max_length=20)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(choices=[('grade_7', '初一'), ('grade_8', '初二'), ('grade_9', '初三'), ('grade_10', '高一'), ('grade_11', '高二'), ('grade_12', '高三')], max_length=10)),
                ('hobby_tags', models.JSONField(default=list)),
                ('concern_tags', models.JSONField(default=list)),
                ('other_hobby_text', models.TextField(blank=True, default='')),
                ('other_concern_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
