# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name_cn', models.CharField(max_length=64)),
                ('description_cn', models.TextField()),
                ('trigger_rule', models.JSONField(default=dict)),
                ('icon', models.CharField(default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('mood_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('mood_value', models.IntegerField()),
                ('emoji', models.CharField(max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('context', models.CharField(choices=[('manual', '手动记录'), ('before_teaching', '教学前'), ('after_teaching', '教学后')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_records', to='teaching.teachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_records',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mood.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
