# Generated by Django 6.0.5 on 2026-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodrecord',
            name='context',
            field=models.CharField(choices=[('manual', '手动记录'), ('before_teaching', '教学前'), ('after_teaching', '教学后'), ('after_testing', '测试后')], max_length=16),
        ),
    ]
