# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('risk_event_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('trigger_text', models.TextField()),
                ('detection_source', models.CharField(choices=[('keyword', '关键词'), ('ai', 'AI语义'), ('both', '两者')], default='keyword', max_length=10)),
                ('action_taken', models.TextField(blank=True, default='')),
                ('session_stopped', models.BooleanField(default=True)),
                ('follow_up_mode', models.CharField(default='onsite_manual_followup', max_length=32)),
                ('exported_flag', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='teaching.teachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_events',
            },
        ),
    ]
