# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('attempt_no', models.IntegerField(default=1)),
                ('rag_context_ids', models.JSONField(default=list)),
                ('total_questions', models.IntegerField(default=5)),
                ('correct_count', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('user_terminated', '用户终止')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='teaching.teachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('question_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('scenario_text', models.TextField(blank=True, default='')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.CharField(max_length=4)),
                ('user_answer', models.CharField(blank=True, default='', max_length=4)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, default='')),
                ('source_chunk_ids', models.JSONField(default=list)),
                ('image_prompt', models.TextField(blank=True, default='')),
                ('temporary_image_url', models.TextField(blank=True, default='')),
                ('image_model', models.CharField(blank=True, default='', max_length=64)),
                ('image_generated_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test')),
            ],
            options={
                'db_table': 'test_questions',
            },
        ),
    ]
