# Generated by Django 6.0.5 on 2026-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_add_created_at_to_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='post_mood_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
