# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('log_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('viewer_role', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=12)),
                ('report_type', models.CharField(blank=True, default='', max_length=32)),
                ('export_format', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_views', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_access_logs',
            },
        ),
    ]
