# Generated by Django 6.0.5 on 2026-05-07 08:17

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('session_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('selected_module', models.CharField(blank=True, default='', max_length=64)),
                ('selected_skill', models.CharField(blank=True, default='', max_length=128)),
                ('selection_reason', models.TextField(blank=True, default='')),
                ('rag_context_ids', models.JSONField(default=list)),
                ('teaching_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('stopped_by_risk', '风险中止'), ('user_terminated', '用户终止')], default='ongoing', max_length=20)),
                ('pre_mood_id', models.CharField(blank=True, default='', max_length=36)),
                ('post_mood_id', models.CharField(blank=True, default='', max_length=36)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统'), ('tool', '工具')], max_length=12)),
                ('content', models.TextField()),
                ('modality', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teaching.teachingsession')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
