# Generated by Django 6.0.5 on 2026-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_teachingsession_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_prompt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='personal_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teachingsession',
            name='phase',
            field=models.CharField(choices=[('pre_mood_recording', '教学前心情记录'), ('personal_inquiry', '个人情况了解'), ('info_collection', '信息收集'), ('skill_selection', '技能选择'), ('rag_retrieval_for_teaching', 'RAG教学检索'), ('teaching', '教学中')], default='pre_mood_recording', max_length=30),
        ),
    ]
