# Generated by Django 6.0.5 on 2026-07-12 15:29

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMASubmission',
            fields=[
                ('submission_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sad_score', models.IntegerField()),
                ('anxious_score', models.IntegerField()),
                ('angry_score', models.IntegerField()),
                ('calm_score', models.IntegerField()),
                ('hopeful_score', models.IntegerField()),
                ('distress_score', models.IntegerField()),
                ('nssi_urge_score', models.IntegerField()),
                ('used_dbt_skill', models.BooleanField()),
                ('dbt_skills_used', models.JSONField(default=list)),
                ('skill_effectiveness_score', models.IntegerField(blank=True, null=True)),
                ('medical_doctor_visit', models.BooleanField(default=False)),
                ('medical_group_therapy', models.BooleanField(default=False)),
                ('medical_medication_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ema_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ema_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
