# Generated by Django 6.0.5 on 2026-05-09 02:59

import dbt_platform.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0002_add_session_phase'),
        ('testing', '0003_add_post_mood_id_to_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSynthesisLog',
            fields=[
                ('synthesis_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('model', models.CharField(default='speech-2.8-turbo', max_length=64)),
                ('voice', models.CharField(blank=True, default='', max_length=64)),
                ('temporary_audio_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_syntheses', to='teaching.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_syntheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_synthesis_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTranscriptionLog',
            fields=[
                ('transcription_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('transcribed_text', models.TextField(blank=True, default='')),
                ('model', models.CharField(default='', max_length=64)),
                ('audio_duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='teaching.teachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_transcription_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGenerationLog',
            fields=[
                ('image_id', models.CharField(default=dbt_platform.utils.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('model', models.CharField(default='image-01', max_length=64)),
                ('temporary_image_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('teaching_scene', '教学情景'), ('test_illustration', '测试题配图'), ('manual', '手动生成')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generations', to='teaching.teachingsession')),
                ('test_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generations', to='testing.testquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
