# Generated by Django 6.0.5 on 2026-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosynthesislog',
            name='model',
            field=models.CharField(default='volcengine-tts', max_length=64),
        ),
    ]
